### ISSUE TITLE
Release 0.26.0 is not pre amalgamated

### ISSUE THREAD

**Issue by yaourt** [resilar/sqleet#20]
The 0.26.0 releases archives (zip and tarball) are not pre "amalgamated" ...

- https://github.com/resilar/sqleet/archive/sqleet-v0.26.0.zip

- https://github.com/resilar/sqleet/archive/sqleet-v0.26.0.tar.gz

In previous releases, the downloaded content was ready to be used.

Is this something desired  or an issue ?
If this is desired, then the README should be also updated accordingly ("Compiling" paragraph)

> To use sqleet as a library, the recommended way is to download a preconfigured release package instead of cloning the master. The contained sqleet.c and sqleet.h files are drop-in replacements for the official sqlite3.c amalgamation and sqlite3.h header. The C interface of the sqleet encryption extension is described in section SQLite3 encryption API.

PS: Thanks for this nice piece of work !

**Comment by resilar** [comment]
My bad, the tag pointed to wrong commit (branch [v0.26.0](https://github.com/resilar/sqleet/tree/v0.26.0) was OK). The v0.26.0 tag & release is now fixed. Thanks for reporting the issue.
