### ISSUE TITLE
python instructions

### ISSUE THREAD

**Issue by pouyamiralayi** [resilar/sqleet#21]
Hello and thanks for this awesome project.
I just wanted to know how can i use this library as the default sqlite library in my python projects?
i am naive developer i was curios if i should download the source of sqlite3 amalgamation and provide c headers of this project to compile with. am i right?
BTW what should i do after compiling sqlite3 for integrating it into my python projects?
thanks in advance.

**Comment by resilar** [comment]
I am not aware of an easy way to use sqleet in Python projects. However, you are not completely out of luck thanks to [pysqlite3](https://github.com/coleifer/pysqlite3) by Charles Leifer (see [this blog post](http://charlesleifer.com/blog/compiling-sqlite-for-use-with-python-applications/) for his instructions). You can compile sqleet for use in Python virtualenv as follows:

```
% virtualenv -p /usr/bin/python3 sqleet
% cd sqleet
% source bin/activate
% git clone https://github.com/coleifer/pysqlite3
% cd pysqlite3
% wget https://github.com/resilar/sqleet/releases/download/v0.27.1/sqleet-v0.27.1-amalgamation.tar.gz
% tar -xvf sqleet-v0.27.1-amalgamation.tar.gz
% cp sqleet-v0.27.1/sqleet.c sqlite3.c
% cp sqleet-v0.27.1/sqleet.h sqlite3.h
% python setup.py build_static
% python setup.py install
% python3
Python 3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pysqlite3 import dbapi2 as sqleet
>>> sqleet.sqlite_version
'3.27.1'
```

The process is actually rather simple thanks to the standalone nature of sqleet (there is no need to configure OpenSSL dependencies or other stuff). Usage on Windows/Mac probably requires a bit more effort and I cannot help with that at the moment.

---

Ultimately, we would like to have `pysqleet` Python package that can be installed with PIP for any operating system. This, however, is a project for someone else than me.

Leave this issue open until we have proper Python support. It can take a long time though.

**Comment by pouyamiralayi** [comment]
Well awesome! your kind answer was really helpful to me.
Thanks in advance.

**Comment by resilar** [comment]
I created a GitHub organization for sqleet: [https://github.com/sqleet](https://github.com/sqleet). It is currently empty, but the plan is to add repos of sqleet wrappers/packages for different programming languages and target platforms (for example, Android/iOS wrappers and Python/node.js packages). This main sqleet repo should also be transferred to that organization at some point in the future.

**Obligatory disclaimer**: Hold your horses! This is a long-term plan for upcoming years, so do not expect specialized support for your favorite language anytime soon. Unless, of course, you are willing to implement that support yourself. Contact me if you *want* your wrapper/package to be added to the sqleet organization.

**Comment by resilar** [comment]
Apparently someone has made a pypi package for sqleet. https://pypi.org/project/apsw-sqleet/

Combining all existing sqleet wrappers/packages to one place would be nice. However, not in the scope of this issue. Closing.

**Comment by clach04** [comment]
Also https://pypi.org/project/pysqleet/
