### ISSUE TITLE
SQLeet manifests itself as SQLite. Is it intentional?

### ISSUE THREAD

**Issue by johnfound** [resilar/sqleet#28]
In SQLeet, the string on sqlite3_version and sqlite3_sourceid() returns the version and commit ID of the SQLite, not of SQLeet. 

Is this behavior intentional? Is there a way for the application to check and display the version of SQLeet?

**Comment by resilar** [comment]
SQLite3 version *number* matches sqleet version as explained in [README.md#Versioning-Scheme](https://github.com/resilar/sqleet#versioning-scheme). The `sourceid` is more complicated, but I think the current behavior is acceptable (I'd still like to hear if this is an issue for someone's use case). After all, sqleet is an *extension* of SQLite3 the same way as the official [SQLite Encryption Extension (SEE)](https://www.sqlite.org/see/doc/release/www/index.wiki) which also does not modify the `sourceid` to my knowledge.

If version numbers are too inaccurate, then exposing sqleet commit hash somehow might be a good idea. However, I do not see an easy way to implement this without complicating the compilation/build process, so let's reconsidering this feature later if there is real demand for exact sqleet commit ids.

Closing, feel free to reopen if it feels necessary. Thanks for the feedback.
